### ISSUE TITLE
Pipeline with probe option

### ISSUE THREAD

**Issue by miRNA67** [leylabmpi/CoreGenomePrimers#4]
Dear,

I completed the test running without probe successfully. Now, I am running the test to obtain primers and probes with the option: internal_oligo: --make-oligo 1 --int-opt-size 20 --int-opt-tm 60

But I have the next error:

Activating conda environment: .snakemake/conda/7ade34bbbe408aa50293b46a74aeb125_
[Wed Oct  5 18:38:41 2022]
Finished job 112.
2 of 93 steps (2%) done
Select jobs to execute...
[Wed Oct  5 18:38:42 2022]
Error in rule primers_design:
    jobid: 84
    output: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/8/primers_degen.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/8/primers_expand.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/8/primers.tsv
    log: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/8.log (check log file(s) for error message)
    conda-env: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/.snakemake/conda/7ade34bbbe408aa50293b46a74aeb125_
    shell:
        
        export PATH=$CONDA_PREFIX/bin:$PATH
        PREFIX=`echo "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/8/primers.tsv" | perl -pe 's/\.tsv$//'`
        /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py --consensus-threshold 0.34 --num-raw-primers 1000 --num-final-primers 10 --opt-size 20 --min-size 18 --max-size 26 --opt-prod-size 150 --min-prod-size 100 --max-prod-size 250 --opt-tm 62 --min-tm 54 --max-tm 70 --max-tm-diff 2.5 --oligo-DNA 50 --salt-monovalent 50 --salt-divalent 1.5 --dNTPs 0.2 --opt-gc 50 --min-gc 25 --max-gc 75 --max-degeneracy 128 --max-degeneracy-3prime 6 --window-3prime 5 --make-oligo 1 --int-opt-size 20 --int-opt-tm 60           --prefix $PREFIX /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/clusters_core/cds/cluster_8.afa 2> /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/8.log 1>&2
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Wed Oct  5 18:38:43 2022]
Error in rule primers_design:
    jobid: 56
    output: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/2/primers_degen.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/2/primers_expand.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/2/primers.tsv
    log: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/2.log (check log file(s) for error message)
    conda-env: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/.snakemake/conda/7ade34bbbe408aa50293b46a74aeb125_
    shell:
        
        export PATH=$CONDA_PREFIX/bin:$PATH
        PREFIX=`echo "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/2/primers.tsv" | perl -pe 's/\.tsv$//'`
        /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py --consensus-threshold 0.34 --num-raw-primers 1000 --num-final-primers 10 --opt-size 20 --min-size 18 --max-size 26 --opt-prod-size 150 --min-prod-size 100 --max-prod-size 250 --opt-tm 62 --min-tm 54 --max-tm 70 --max-tm-diff 2.5 --oligo-DNA 50 --salt-monovalent 50 --salt-divalent 1.5 --dNTPs 0.2 --opt-gc 50 --min-gc 25 --max-gc 75 --max-degeneracy 128 --max-degeneracy-3prime 6 --window-3prime 5 --make-oligo 1 --int-opt-size 20 --int-opt-tm 60           --prefix $PREFIX /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/clusters_core/cds/cluster_2.afa 2> /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/2.log 1>&2
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Wed Oct  5 18:38:43 2022]
Error in rule primers_design:
    jobid: 98
    output: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/3/primers_degen.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/3/primers_expand.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/3/primers.tsv
    log: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/3.log (check log file(s) for error message)
    conda-env: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/.snakemake/conda/7ade34bbbe408aa50293b46a74aeb125_
    shell:
        
        export PATH=$CONDA_PREFIX/bin:$PATH
        PREFIX=`echo "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/3/primers.tsv" | perl -pe 's/\.tsv$//'`
        /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py --consensus-threshold 0.34 --num-raw-primers 1000 --num-final-primers 10 --opt-size 20 --min-size 18 --max-size 26 --opt-prod-size 150 --min-prod-size 100 --max-prod-size 250 --opt-tm 62 --min-tm 54 --max-tm 70 --max-tm-diff 2.5 --oligo-DNA 50 --salt-monovalent 50 --salt-divalent 1.5 --dNTPs 0.2 --opt-gc 50 --min-gc 25 --max-gc 75 --max-degeneracy 128 --max-degeneracy-3prime 6 --window-3prime 5 --make-oligo 1 --int-opt-size 20 --int-opt-tm 60           --prefix $PREFIX /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/clusters_core/cds/cluster_3.afa 2> /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/3.log 1>&2
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Wed Oct  5 18:38:43 2022]
Error in rule primers_design:
    jobid: 70
    output: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/1/primers_degen.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/1/primers_expand.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/1/primers.tsv
    log: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/1.log (check log file(s) for error message)
    conda-env: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/.snakemake/conda/7ade34bbbe408aa50293b46a74aeb125_
    shell:
        
        export PATH=$CONDA_PREFIX/bin:$PATH
        PREFIX=`echo "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/1/primers.tsv" | perl -pe 's/\.tsv$//'`
        /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py --consensus-threshold 0.34 --num-raw-primers 1000 --num-final-primers 10 --opt-size 20 --min-size 18 --max-size 26 --opt-prod-size 150 --min-prod-size 100 --max-prod-size 250 --opt-tm 62 --min-tm 54 --max-tm 70 --max-tm-diff 2.5 --oligo-DNA 50 --salt-monovalent 50 --salt-divalent 1.5 --dNTPs 0.2 --opt-gc 50 --min-gc 25 --max-gc 75 --max-degeneracy 128 --max-degeneracy-3prime 6 --window-3prime 5 --make-oligo 1 --int-opt-size 20 --int-opt-tm 60           --prefix $PREFIX /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/clusters_core/cds/cluster_1.afa 2> /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/1.log 1>&2
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Wed Oct  5 18:38:43 2022]
Error in rule primers_design:
    jobid: 77
    output: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/5/primers_degen.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/5/primers_expand.fna, /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/5/primers.tsv
    log: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/5.log (check log file(s) for error message)
    conda-env: /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/.snakemake/conda/7ade34bbbe408aa50293b46a74aeb125_
    shell:
        
        export PATH=$CONDA_PREFIX/bin:$PATH
        PREFIX=`echo "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/primers_raw/cds/5/primers.tsv" | perl -pe 's/\.tsv$//'`
        /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py --consensus-threshold 0.34 --num-raw-primers 1000 --num-final-primers 10 --opt-size 20 --min-size 18 --max-size 26 --opt-prod-size 150 --min-prod-size 100 --max-prod-size 250 --opt-tm 62 --min-tm 54 --max-tm 70 --max-tm-diff 2.5 --oligo-DNA 50 --salt-monovalent 50 --salt-divalent 1.5 --dNTPs 0.2 --opt-gc 50 --min-gc 25 --max-gc 75 --max-degeneracy 128 --max-degeneracy-3prime 6 --window-3prime 5 --make-oligo 1 --int-opt-size 20 --int-opt-tm 60           --prefix $PREFIX /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/tmp/cabana/CoreGenomePrimers_1051914/clusters_core/cds/cluster_5.afa 2> /home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/5.log 1>&2
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Is possible to correct this error?

Thank you!!!

**Comment by nick-youngblut** [comment]
What's in the log (e.g., `/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/tests/output_pecto/logs/cgp/primers/design/cds/5.log`)?

**Comment by miRNA67** [comment]
2022-10-05 18:38:40,204 - Designing primers...
2022-10-05 18:38:43,311 -   No. of raw degen primer sets: 1000
2022-10-05 18:38:43,311 - Calculating degenerate primers...
Traceback (most recent call last):
  File "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py", line 760, in <module>
    main(args)
  File "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py", line 737, in main
    internal_oligo=args.make_oligo)
  File "/home/cabana/Documents/INS/coregenomeprimers/CoreGenomePrimers/bin/scripts/primer_design.py", line 483, in calc_degen
    'degeneracy_3p' : len(degen_3p),
TypeError: object of type 'NoneType' has no len()

**Comment by nick-youngblut** [comment]
I have to admit that I didn't do much testing with probe design. I'll have to look into the problem

**Comment by nick-youngblut** [comment]
I've fixed the error:

```
TypeError: object of type 'NoneType' has no len() in `primer_design.py`
```

...however, I did find that there are still issues with `blastn` and the use of `-negative_taxidlist`, in which certain lists of taxids can cause a `segmentation fault` error. I've reported this to the NCBI, but they often take many days to respond and even longer to fix bugs. I'll update this issue as things progress.

So, you might run into issues with the `blastn` jobs due to `-negative_taxidlist`, but this depends on the taxids included.
